### PR TITLE
changed from bulma css to foundation css

### PR DESCRIPTION
**Pull request by dolinay1**

### CODE REVIEW

**Comment by ryansparker** [comment]
ok

**Comment by ryansparker** [comment]
reviewed

**Comment by ryansparker** [comment]
reviewed

**Comment by ryansparker** [comment]
reviewed

**Review by ryansparker — APPROVED** [review]
reviewed

**Review by TLGeorge — APPROVED** [review]
approved

**Comment by TLGeorge** [comment]
review

**Pull request merged**
